### ISSUE TITLE
Single-sign on

### ISSUE THREAD

**Issue by hitteshahuja** [Panopto/Add-Panopto-Video--button-for-moodle-tinyMCE-editor#1] opened 2014-11-25 12:08 UTC
Hi,
our institution (university of Bath) uses single sign on to connect to our hosted site. Is it possible to implement Single sign on for the tinmyce plugin too ?

**Comment by jmalmsten-panopto** [comment] 2022-02-17 22:36
Hi,

Closing this since the issue is over 6 years old. If you do end up receiving this and are still interested in this feature please re-open the issue.

Thanks, 
Joe Malmsten

**Closed by jmalmsten-panopto** 2022-02-17 22:36 UTC
